default: &default
  adapter: postgresql
  username: your_username_here
  password: your_password_here
  host: your_host_here
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: todolist_development

test:
  <<: *default
  database: todolist_test

production:
  <<: *default
  database: todolist_production
